### ISSUE TITLE
Is this level 155 solvable?

### ISSUE THREAD

**Issue by TomTomRixRix** [douira/island-tiles#7]
I've been trying this level for days now, but couldn't find a solution. I'm wondering if there is any solution or if there is a bug which makes it unsolvable.

<img width="803" alt="grafik" src="https://user-images.githubusercontent.com/13121269/87872452-ac474380-c9b0-11ea-89b4-66bef971fa22.png">

**Comment by douira** [comment]
In theory, all levels should be solvable since I'm pretty sure all the imported levels are solvable. But you're right, there might be a bug in the implementation of the objects that makes it unsolvable. I thought all the element behaviours were pretty consistent though. There might also be an error in the import because the element types were sometimes unclear in the source data. I can have a look at what's going on here. In the mean time, you can skip ahead using the debug mode (at the bottom of the page).

**Comment by douira** [comment]
After looking at this [possible hint ](http://pushy-forum.de/viewtopic.php?f=18&t=324) I might have found the problem: the flying pebble is transported with the teleporter which kinda messes it all up. The pebble being affected by the transporter might be a bug. For the coordinate system the X axis is A,B,C... and the Y axis is 1,2,3... with the origin in the top right corner. The idea is probably to ride the raft to the island with the leaf-stone using the box at P10 as a stopper. The level is probably solvable if the teleporter didn't teleport the flying pebble.

**Comment by douira** [comment]
If this is in fact the issue, the pebble has to be excluded from the blocks that the teleporter teleports. I'd introduce a new composition type like `NonTeleportable` and have the `Teleporter` check if the subject being teleported can be teleported. I can implement a fix sometime soon (I have a lot going on right now though) or you can try and do a PR if you like. ;-)

**Comment by TomTomRixRix** [comment]
That might indeed be the problem, that the pebble is also teleported. Otherwise the level should work. There is also another solution which would simply require one more wodden box or the possibility to move leaves into water.

Anyways, it isn't urgent at all. I just thought I'd let you know about this problem as I've already detected it.
